web/website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .config import Config
from .forms import RegisterForm, LoginForm
from .models import User
from . import db
from flask_login import login_user, logout_user, login_required

bp = Blueprint('auth', __name__)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        print(f"\n[INFO] Form submitted to login!\n")
        user_input = User.query.filter_by(username=form.username.data).first()
        print(f"\nUSER INPUT : {user_input}\n", )
        if user_input and user_input.check_password(input_password=form.password.data):
            login_user(user_input)
            # login_user(user, remember=form.remember.data)
            flash(
                f"You are logged in! Welcome "
                f"{user_input.username}", category='success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('views.home'))
        else:
            flash('Wrong password! Please try again.', category='danger')
    return render_template('login.html', form=form)


@bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        print(f"\n[INFO] Creating user ...\n")
        user_input = User(username=form.username.data,
                          password=form.password.data)
        db.session.add(user_input)
        db.session.commit()
        login_user(user_input)
        flash(
            f"Account created successfully! Welcome "
            f"{user_input.username}", category='success')
        return redirect(url_for('views.home'))
    return render_template('register.html', form=form)


@bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash("Logged out successfully!", category="primary")
    return redirect(url_for('views.home'))

web/website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify
from flask_login import login_required, current_user
from injector import inject
import pandas as pd
import numpy as np
import time
import os
from .config import Config
from .knn_model import get_anime_rows, get_recommendation
from .embedding_model import InitializedModel
from .models import Bookmark
from .forms import RemoveBookmarkForm
from . import db

bp = Blueprint('views', __name__)


def load_df(full_df=True, sort_score=False):
    if full_df:
        df = pd.read_csv(os.path.join(Config.DATA_PATH, 'full_anime_info.csv'))
    else:
        df = pd.read_csv(os.path.join(Config.DATA_PATH, 'anime_info.csv'))

    if sort_score:
        df.sort_values('Score', ascending=False,
                       inplace=True, ignore_index=True)

    # fix missing scores
    fix_scores(df)
    return df


def fix_scores(df):
    df['Score'] = df['Score'].apply(lambda x: format(x, ".2f"))
    df['Score'].replace('nan', r'N/A', inplace=True)


def df_row2dict(df):
    # to change a single DataFrame row into dictionary format
    return df.to_dict(orient='records')[0]


def get_top_animes(top_k=48):
    df = load_df(full_df=False, sort_score=True)
    return df.head(top_k)


def find_bookmark(anime_id, return_bookmarked=False):
    # Only check for bookmark if user is logged in
    bookmark, bookmarked = None, None
    if current_user.is_authenticated:
        bookmark = Bookmark.query.filter_by(
            user_id=current_user.id, anime_id=anime_id).first()
        bookmarked = True if bookmark else False
    if return_bookmarked:
        return bookmarked
    return bookmark


def add_or_remove_bookmark(anime_id):
    bookmark = find_bookmark(anime_id)
    if bookmark:
        db.session.delete(bookmark)
        db.session.commit()
    else:
        bookmark = Bookmark(user_id=current_user.id, anime_id=anime_id)
        db.session.add(bookmark)
        db.session.commit()


@bp.route('/home')
@bp.route('/')
def home():
    df = get_top_animes()
    return render_template('home.html', anime_info_df=df)


@bp.route('/about')
def about():
    return render_template('about.html')


@bp.route('/query')
def search():
    # Convert to string to only search by name
    anime_name = request.args.get('anime_name', type=str)
    print(f"\n[INFO] Anime to search for: {anime_name}\n", )
    df = load_df()
    df = get_anime_rows(df, anime_name)
    # To replace unknown values into a max value to sort by popularity
    df['Popularity'].replace(0, 20000, inplace=True)
    df.sort_values('Popularity', ignore_index=True, inplace=True)
    return render_template('search.html', anime_info_df=df)


@bp.route('/anime/<int:anime_id>', methods=['GET', 'POST'])
def anime(anime_id):
    if request.method == "GET":
        df = load_df()
        df = df.loc[df['MAL_ID'] == anime_id]
        anime_info = df_row2dict(df)

        bookmarked = find_bookmark(anime_id, return_bookmarked=True)

        return render_template('anime.html', anime_info=anime_info, bookmarked=bookmarked)

    if request.method == "POST":
        add_or_remove_bookmark(anime_id)
        return redirect(url_for('views.anime', anime_id=anime_id))


@inject
@bp.route('/recommend/<int:anime_id>', methods=['GET', 'POST'])
def recommend(anime_id, model: InitializedModel):
    # Using dependency injection resulted in much faster loading times
    if request.method == "GET":
        start_time = time.time()
        # anime_row, rec_df = get_recommendation(anime_id, k=21)
        anime_row, rec_df = model.get_recommendation(anime_id, k=30)
        fix_scores(rec_df)
        time_elapsed = time.time() - start_time
        print(f"[INFO] Time elapsed for recommendation: "
              f"{time_elapsed:.2f} seconds.\n")
        anime_info = df_row2dict(anime_row)
        rec_df.reset_index(drop=True, inplace=True)

        bookmarked = find_bookmark(anime_id, return_bookmarked=True)

        return render_template('recommend.html',
                               anime_info=anime_info,
                               bookmarked=bookmarked,
                               rec_df=rec_df)

    if request.method == "POST":
        add_or_remove_bookmark(anime_id)
        return redirect(url_for('views.recommend', anime_id=anime_id))


@bp.route('/bookmarks', methods=['GET', 'POST'])
@login_required
def bookmarks():
    df = load_df(full_df=False)
    remove_bookmark_form = RemoveBookmarkForm()
    if request.method == "GET":
        page = request.args.get('page', 1, type=int)
        per_page = 10
        bookmarks = Bookmark.query.filter_by(user_id=current_user.id).order_by(
            Bookmark.date_created.desc()).paginate(page=page, max_per_page=per_page)

        # Create a dictionary to sort the df by the order of the bookmarks
        anime_ids_dict = {bm.anime_id: i for i,
                          bm in enumerate(bookmarks.items)}
        bookmark_df = df.loc[df['MAL_ID'].isin(anime_ids_dict.keys())].copy()
        bookmark_df['Order'] = bookmark_df['MAL_ID'].map(anime_ids_dict)
        bookmark_df.sort_values('Order', inplace=True)

        # Create index to show the each bookmark number in the sorted order
        start_idx = (page - 1) * per_page
        end_idx = (page - 1) * per_page + len(bookmark_df)
        bookmark_df.index = np.arange(start_idx, end_idx)

        # bookmark_df.reset_index(drop=True, inplace=True)
        return render_template('bookmarks.html',
                               remove_bookmark_form=remove_bookmark_form,
                               df=bookmark_df,
                               bookmarks=bookmarks)

    if request.method == "POST":
        # Get the page to redirect to the current page after deleting bookmark
        page = request.args.get('page', 1, type=int)
        df_length = request.form.get('df_length', type=int)
        # redirect to the first page if there is no more bookmark
        #   at the current page
        if df_length == 1:
            page = 1

        anime_id = request.form.get('anime_id_to_remove', type=int)
        bookmark = find_bookmark(anime_id)
        if bookmark:
            print(f"\nRemoving bookmark for Anime ID: {anime_id}\n")
            db.session.delete(bookmark)
            db.session.commit()
            anime_name = df.loc[df['MAL_ID'] == anime_id, 'Name'].values[0]
            flash(f'Removed "{anime_name}" from bookmarks.',
                  category='success')
        return redirect(url_for('views.bookmarks', page=page))

web/website/templates/about.html
{% extends 'base.html' %}

{% block title %}
About the Website
{% endblock %}

{% block content %}

<div class="container">
  <div id="about-page">
    <section class="about">
      <div class="my-3">
        <h1 class="col p-2 anime-heading border-bottom border-custom">
          About the Website
        </h1>
      </div>
      <p>
        This website was built to recommend Animes using a backend system that was built with an AI model, specifically
        a collaborative filtering model.
      </p>
      <p>
        It was built with the motivation of showcasing the ability of AI model to predict similar Animes based on how
        well the users have rated the other Animes compared to the current Anime that was asked for
        recommendations. In simple words, the AI model will give Anime recommendations that are similar to the current
        Anime based on most of the user preferences.
      </p>
      <p>
        If you are interested to know more about the technical details. Feel free to visit the <a class="custom-link"
          href="https://github.com/ansonnn07/Anime-Recommendation" target="_blank">GitHub repo</a>.
      </p>
    </section>

    <section class="guide">
      <div class="mt-4 mb-3">
        <h1 class="col p-2 anime-heading border-bottom border-custom">
          How to Use the Website
        </h1>
      </div>
      <p>
        Just try to search for Animes by name at the top right search box!
        Or simply click on any Animes at the Home Page.
        Then try to ask for recommendations by clicking the "Recommend Similar Animes" button!
      </p>
      <p>
        You can also register for an account and use the feature of "Bookmarking" Animes that you might want to save for
        later. And don't forget your password as this website has not implemented a password reset function yet!
      </p>
      <p>
        <strong>NOTE:</strong> The login function might be gone when you are visiting this website, because I might have
        already taken it down as it would use up unnecessary resources.
      </p>
    </section>
  </div>
</div>

{% endblock %}

web/website/templates/anime.html
{% extends 'base.html' %}

{% block title %}
{{ anime_info['Name'] }}
{% endblock %}

{% block content %}

<!-- Loader -->
<div id="loader">
  <h2>Loading <span class="animating-dots">...</span></h2>
</div>

<!-- Heading -->
<header class="anime-page container-md my-3">
  <div class="p-1 d-flex justify-content-start align-items-center mx-1 border-bottom border-custom">
    <div>
      <div class="anime-heading">
        {{ anime_info['Name']|e }}
      </div>
    </div>
    {% if current_user.is_authenticated %}
    <div>
      <form method="POST">
        <button type="submit" onclick="turnBookmark()" class="btn btn-custom-secondary mx-3">
          {% if bookmarked %}
          <i class="bi bi-bookmark-check-fill" id="bookmark-icon"></i>
          {% else %}
          <i class="bi bi-bookmark" id="bookmark-icon"></i>
          {% endif %}
        </button>
      </form>
    </div>
    {% endif %}
  </div>
</header>

<!-- Anime info -->
<section class="anime-page container-md mt-5">
  <div class="row justify-content-evenly">
    <div class="col-md-4">
      <div class="d-flex justify-content-center">
        <a href="{{ anime_info['img_url'] }}" target="_blank">
          <img class='img-fluid' src="{{ anime_info['img_url'] }}" alt="anime image">
        </a>
      </div>
    </div>
    <div class="col-md-5 p-2">
      <div class="rating">
        <div class="rating-score d-flex align-items-center">
          <span class="pe-2 fs-5">Score:</span>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
            class="bi bi-star-fill rating-star" viewBox="0 0 16 16">
            <path
              d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
          </svg>
          <div class='rating-score fs-5'>
            {{ anime_info['Score'] }}
          </div>
        </div>
      </div>
      <div class="info">
        <div class="mb-1">
          <span class="info-heading fs-5">Type:</span>
          {{ anime_info['Type'] }}
        </div>
        <div class="mb-1">
          <span class="info-heading fs-5">Episodes:</span>
          {{ anime_info['Episodes'] }}
        </div>
        <div class="mb-1">
          <span class="info-heading fs-5">Aired:</span>
          {{ anime_info['Aired'] }}
        </div>
        <div class="mb-1">
          <h2 class="info-heading fs-5">Genres:</h2>
          {{ anime_info['Genres'] }}
        </div>
      </div>
      <div class="container-fluid mt-4">
        <a href="{{ 'https://myanimelist.net/anime/{}'.format(anime_info['MAL_ID']) }}" target="_blank">
          <button type="button" class="btn btn-custom">
            Open in MyAnimeList
          </button>
        </a>
      </div>
      <div class="container-fluid mt-3">
        <a href="{{ url_for('views.recommend', anime_id=anime_info['MAL_ID']) }}">
          <button type="button" onclick="loader()" class="btn btn-custom-secondary">
            Recommend Similar Animes
          </button>
        </a>
      </div>
    </div>
  </div>
</section>

<!-- Anime synopsis -->
<section class="container-md mt-3 synopsis">
  <div class="row mx-1 synopsis-heading border-bottom border-custom fs-5">
    Synopsis
  </div>
  <div class="row mx-1">
    {{ anime_info['new_synopsis'] }}
  </div>
</section>

{% endblock %}

web/website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap 5.0 CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

  <!-- Custom CSS -->
  <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

  <!-- Custom fonts -->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link
    href="https://fonts.googleapis.com/css2?family=Limelight&family=Roboto:wght@400;500;700&family=ZCOOL+KuaiLe&display=swap"
    rel="stylesheet">

  <!-- Bootstrap icons -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

  <!-- favicon icon for browser -->
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

  <!-- Title -->
  <title>
    {% block title %}

    {% endblock %}
  </title>
</head>

<body>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-md navbar-dark nav-bg">
    <div class="container-fluid px-4">
      <a class="navbar-brand" href="{{ url_for('views.home')}}">Anime</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('views.home')}}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('views.about')}}">About</a>
          </li>
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('views.bookmarks') }}">Bookmarks</a>
          </li>
        </ul>
        <ul class="navbar-nav me-3">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
          </li>
        </ul>
        {% else %}
        </ul>
        <ul class="navbar-nav me-3">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
          </li>
        </ul>
        {% endif %}
        <form action="{{ url_for('views.search') }}" class="d-flex">
          <div class="input-group">
            <input class="form-control" type="search" name="anime_name" placeholder="Search Anime"
              aria-label="Search Anime" aria-describedby="searchGroup" required="required">
            <div class="input-group-text" id="searchGroup">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                class="bi bi-search" viewBox="0 0 16 16">
                <path
                  d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
              </svg>
            </div>
          </div>
        </form>
      </div>
    </div>
  </nav>

  <!-- Flash messages -->
  <div class="container-md mt-1">
    <div class="row justify-content-center">
      <div class="col p-1 max-width-800">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
      </div>
    </div>
  </div>

  <!-- Content Block -->
  {% block content %}

  {% endblock %}

  <!-- Footer -->
  <footer class="footer-bg">
    <div class="container text-center py-3">
      <p class="footer-text">© 2023 Anime Website. All rights reserved.</p>
    </div>
  </footer>

  <!-- Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
    crossorigin="anonymous"></script>

  <script src="{{ url_for('static', filename='index.js') }}"></script>
</body>

</html>

web/website/templates/bookmarks.html
{% extends 'base.html' %}

{% block title %}
Bookmarks
{% endblock %}

{% block content %}

<div class="container-lg">

  <div class="row mt-3">
    <h1 class="col anime-heading border-bottom border-custom">
      Bookmarks
    </h1>
  </div>

  <!-- Pagination at top -->
  <div class="text-end mb-2">
    {% if bookmarks.pages == 1 %}
    {% else %}
    <a href="{{ url_for('views.bookmarks', page=bookmarks.prev_num) }}" class="btn btn-custom-secondary 
       {% if bookmarks.page == 1 %} disabled {% endif %}">
      &laquo;
    </a>
    {% for page_num in bookmarks.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
    {% if bookmarks.page == page_num %}
    <a class="btn btn-custom" href="{{ url_for('views.bookmarks', page=page_num) }}">{{ page_num }}</a>
    {% else %}
    <a class="btn btn-custom-secondary" href="{{ url_for('views.bookmarks', page=page_num) }}">{{ page_num }}</a>
    {% endif %}
    {% else %}
    ...
    {% endif %}
    {% endfor %}
    <a href="{{ url_for('views.bookmarks', page=bookmarks.next_num) }}" class="btn btn-custom-secondary 
       {% if bookmarks.page == bookmarks.pages %} disabled {% endif %}">
      &raquo;
    </a>
    {% endif %}
  </div>

  <!-- Bookmarks Table -->
  <table class="table table-bordered table-bg border-custom mb-2">
    <thead>
      <tr>
        <th scope="col" class="number-col">#</th>
        <th scope="col" class="img-col">Image</th>
        <th scope="col" class="anime-col">Anime</th>
        <th scope="col" class="status-col">Status</th>
      </tr>
    </thead>
    <tbody>
      {% for df_row in df.itertuples() %}
      <tr>
        <th scope="row" class="number-cell">
          {{ df_row.Index + 1 }}
        </th>
        <td class="img-cell">
          <a href="{{ url_for('views.anime', anime_id=df_row.MAL_ID) }}">
            <img src="{{ df_row.img_url }}" alt="anime image">
          </a>
        </td>
        <td class="anime-cell">
          <div>
            <a href="{{ url_for('views.anime', anime_id=df_row.MAL_ID) }}">
              {{ df_row.Name|e }}
            </a>
          </div>
          <div class="d-flex align-items-center mt-2">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
              class="bi bi-star-fill rating-star ms-0" viewBox="0 0 16 16">
              <path
                d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
            </svg>
            <span class="rating-score fs-5">{{ df_row.Score }}</span>
          </div>
        </td>

        <td class="status-cell">
          <form method="POST">
            {{ remove_bookmark_form.hidden_tag() }}
            <!-- inputs with type="hidden" are used to send data to backend-->
            <input id="df_length" name="df_length" type="hidden" value="{{ df|length }}">
            <input id="anime_id_to_remove" name="anime_id_to_remove" type="hidden" value="{{ df_row.MAL_ID }}">
            {{ remove_bookmark_form.submit(class="btn btn-custom remove-button") }}
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <!-- Pagination at bottom -->
  <div class="text-end mb-4">
    {% if bookmarks.pages == 1 %}
    {% else %}
    <a href="{{ url_for('views.bookmarks', page=bookmarks.prev_num) }}" class="btn btn-custom-secondary 
       {% if bookmarks.page == 1 %} disabled {% endif %}">
      &laquo;
    </a>
    {% for page_num in bookmarks.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
    {% if bookmarks.page == page_num %}
    <a class="btn btn-custom" href="{{ url_for('views.bookmarks', page=page_num) }}">{{ page_num }}</a>
    {% else %}
    <a class="btn btn-custom-secondary" href="{{ url_for('views.bookmarks', page=page_num) }}">{{ page_num }}</a>
    {% endif %}
    {% else %}
    ...
    {% endif %}
    {% endfor %}
    <a href="{{ url_for('views.bookmarks', page=bookmarks.next_num) }}" class="btn btn-custom-secondary 
       {% if bookmarks.page == bookmarks.pages %} disabled {% endif %}">
      &raquo;
    </a>
    {% endif %}
  </div>

</div>

{% endblock %}

web/website/templates/login.html
{% extends 'base.html' %}

{% block title %}
Login
{% endblock %}

{% block content %}

<div class="container-md">
  <div id="form-custom">
    <div class="anime-heading mt-0 mb-4 fs-3 border-bottom border-custom">
      Login
    </div>
    <form method="POST">
      {{ form.hidden_tag() }}
      <div class="mb-3">
        <!-- <label for="username" class="form-label">Username</label> -->
        <!-- <input type="text" class="form-control" id="username"> -->
        {{ form.username.label(class="form-label") }}
        {% if form.username.errors %}
        {{ form.username(class="form-control is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.username.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.username(class="form-control", id="username", placeholder="Username") }}
        {% endif %}
      </div>
      <div class="mb-3">
        <!-- <label for="password" class="form-label">Password</label> -->
        <!-- <input type="password" class="form-control" id="password"> -->
        {{ form.password.label(class="form-label") }}
        {% if form.password.errors %}
        {{ form.password(class="form-control is-invalid", id="password") }}
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.password(class="form-control", id="password", placeholder="Password") }}
        {% endif %}
      </div>
      <div class="mb-3 form-check">
        <input type="checkbox" onclick=show_password() class="form-check-input" id="passwordCheck">
        <label class="form-check-label" for="passwordCheck">Show Password</label>
      </div>
      <!-- <button type="submit" class="btn btn-custom-secondary">Login</button> -->
      {{ form.submit(class="btn btn-custom-secondary")}}
    </form>
    <footer id="form-footer-text">
      Don't have an account?
      <a href="{{ url_for('auth.register') }}" class="custom-link">Register here</a>.
    </footer>
  </div>
</div>

{% endblock %}

web/website/templates/register.html
{% extends 'base.html' %}

{% block title %}
Register
{% endblock %}

{% block content %}

<div class="container-md">
  <div id="form-custom">
    <div class="anime-heading mt-0 mb-4 fs-3 border-bottom border-custom">
      Register
    </div>
    <form method="POST">
      {{ form.hidden_tag() }}
      <div class="mb-3">
        <!-- <label for="username" class="form-label">Username</label> -->
        <!-- <input type="text" class="form-control" id="username"> -->
        {{ form.username.label(class="form-label") }}
        {% if form.username.errors %}
        {{ form.username(class="form-control is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.username.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.username(class="form-control", id="username", placeholder="Username") }}
        {% endif %}
      </div>
      <div class="mb-3">
        <!-- <label for="password" class="form-label">Password</label> -->
        <!-- <input type="password" class="form-control" id="password"> -->
        {{ form.password.label(class="form-label") }}
        {% if form.password.errors %}
        {{ form.password(class="form-control is-invalid", id="password") }}
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.password(class="form-control", id="password", placeholder="Password") }}
        {% endif %}
      </div>
      <div class="mb-3">
        <!-- <label for="confirmPassword" class="form-label">Confirm Password</label> -->
        <!-- <input type="password" class="form-control" id="confirmPassword"> -->
        {{ form.confirm_password.label(class="form-label") }}
        {% if form.confirm_password.errors %}
        {{ form.confirm_password(class="form-control is-invalid", id="confirmPassword") }}
        <div class="invalid-feedback">
          {% for error in form.confirm_password.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %}
        {{ form.confirm_password(class="form-control", id="confirmPassword", placeholder="Confirm Password") }}
        {% endif %}
      </div>
      <div class="mb-3 form-check">
        <input type="checkbox" onclick=show_password() class="form-check-input" id="passwordCheck">
        <label class="form-check-label" for="passwordCheck">Show Password</label>
      </div>
      <!-- <button type="submit" class="btn btn-custom-secondary">Register</button> -->
      {{ form.submit(class="btn btn-custom-secondary")}}
    </form>
    <footer id="form-footer-text">
      Already have an account?
      <a href="{{ url_for('auth.login') }}" class="custom-link">Login here</a>.
    </footer>
  </div>
</div>

{% endblock %}